In [ ]:
import tensorflow as tf
import os
import pandas as pd
import numpy as np

In [ ]:
csv_path = '/content/daily.csv'
df = pd.read_csv(csv_path)
df

,date,Gb(i),Gd(i),H_sun,T2m,WS10m,Wdir,Humidity,Pressure
0,1/1/2018,3187.55,898.37,15.073333,11.547778,9.050000,285.555556,63.000000,1020.144444
1,2/1/2018,2617.27,887.88,15.147778,10.875556,8.040000,310.000000,56.222222,1022.655556
2,3/1/2018,1756.67,945.71,15.226667,15.497778,10.267778,261.111111,68.444444,1016.888889
3,4/1/2018,3087.55,936.08,15.313333,15.908889,11.761111,277.777778,66.888889,1014.322222
4,5/1/2018,3369.42,862.01,15.408889,14.043333,2.774444,171.111111,68.111111,1008.133333
...,...,...,...,...,...,...,...,...,...
1091,27/12/2020,961.74,1120.34,14.798889,5.748889,2.107778,95.555556,66.111111,1007.800000
1092,28/12/2020,2105.61,900.47,14.835556,10.088889,9.302222,78.888889,68.333333,989.888889
1093,29/12/2020,3328.21,940.07,14.881111,9.993333,6.098889,63.333333,71.444444,999.288889
1094,30/12/2020,3329.31,867.36,14.932222,8.373333,7.471111,72.222222,71.777778,1007.766667
1095,31/12/2020,943.49,611.74,14.991111,8.981111,2.743333,86.666667,86.444444,1009.944444

In [ ]:
dateTimeAxis = pd.to_datetime(df['date'], format='%d/%m/%Y')
df.index = dateTimeAxis
df[:26]

,date,Gb(i),Gd(i),H_sun,T2m,WS10m,Wdir,Humidity,Pressure
date,,,,,,,,,
2018-01-01,1/1/2018,3187.55,898.37,15.073333,11.547778,9.050000,285.555556,63.000000,1020.144444
2018-01-02,2/1/2018,2617.27,887.88,15.147778,10.875556,8.040000,310.000000,56.222222,1022.655556
2018-01-03,3/1/2018,1756.67,945.71,15.226667,15.497778,10.267778,261.111111,68.444444,1016.888889
2018-01-04,4/1/2018,3087.55,936.08,15.313333,15.908889,11.761111,277.777778,66.888889,1014.322222
2018-01-05,5/1/2018,3369.42,862.01,15.408889,14.043333,2.774444,171.111111,68.111111,1008.133333
2018-01-06,6/1/2018,1834.03,820.76,15.507778,13.468889,8.268889,85.555556,61.333333,1006.322222
2018-01-07,7/1/2018,1966.52,1000.14,15.614444,15.145556,12.764444,66.666667,52.444444,1006.711111
2018-01-08,8/1/2018,460.29,584.49,15.728889,12.950000,7.095556,67.777778,56.777778,1010.011111
2018-01-09,9/1/2018,2366.27,995.59,15.848889,12.134444,6.521111,160.000000,66.888889,1015.944444
2018-01-10,10/1/2018,3121.77,1024.36,15.975556,11.947778,1.511111,191.111111,62.000000,1013.688889
2018-01-11,11/1/2018,2105.30,1131.73,16.108889,10.063333,5.678889,327.777778,73.000000,1011.911111
2018-01-12,12/1/2018,3954.16,889.03,16.246667,9.584444,5.088889,173.333333,65.777778,1018.911111
2018-01-13,13/1/2018,2942.48,869.18,16.392222,10.395556,4.321111,106.666667,69.777778,1020.933333
2018-01-14,14/1/2018,1957.75,973.96,16.543333,11.457778,7.810000,73.333333,65.000000,1017.611111
2018-01-15,15/1/2018,2463.67,940.87,16.702222,10.436667,2.734444,94.444444,67.000000,1022.444444
2018-01-16,16/1/2018,1469.71,955.25,16.863333,13.502222,9.501111,230.000000,68.777778,1015.833333
2018-01-17,17/1/2018,3940.57,898.25,17.035556,11.895556,12.566667,302.222222,43.000000,1016.311111
2018-01-18,18/1/2018,2962.45,1055.69,17.208889,10.768889,8.076667,273.333333,63.222222,1021.633333
2018-01-19,19/1/2018,3772.67,944.99,17.391111,12.570000,8.328889,298.888889,63.111111,1015.500000
2018-01-20,20/1/2018,1354.01,818.10,17.577778,9.790000,6.811111,273.333333,63.000000,1017.677778
2018-01-21,21/1/2018,3727.71,899.68,17.770000,13.476667,11.057778,320.000000,48.666667,1014.400000
2018-01-22,22/1/2018,3378.06,941.81,16.187000,14.420000,10.001000,291.000000,61.500000,1018.490000
2018-01-23,23/1/2018,4308.50,929.92,16.394000,12.951000,9.711000,328.000000,48.800000,1022.520000
2018-01-24,24/1/2018,2785.29,1120.21,16.603000,12.492000,6.503000,83.000000,66.100000,1028.890000
2018-01-25,25/1/2018,1302.18,1098.94,16.817000,13.013000,8.035000,112.000000,68.900000,1022.080000
2018-01-26,26/1/2018,111.58,610.89,17.038000,12.396000,8.139000,77.000000,79.900000,1014.340000

In [ ]:
df = df.drop(['date'], axis=1)
df

,Gb(i),Gd(i),H_sun,T2m,WS10m,Wdir,Humidity,Pressure
date,,,,,,,,
2018-01-01,3187.55,898.37,15.073333,11.547778,9.050000,285.555556,63.000000,1020.144444
2018-01-02,2617.27,887.88,15.147778,10.875556,8.040000,310.000000,56.222222,1022.655556
2018-01-03,1756.67,945.71,15.226667,15.497778,10.267778,261.111111,68.444444,1016.888889
2018-01-04,3087.55,936.08,15.313333,15.908889,11.761111,277.777778,66.888889,1014.322222
2018-01-05,3369.42,862.01,15.408889,14.043333,2.774444,171.111111,68.111111,1008.133333
...,...,...,...,...,...,...,...,...
2020-12-27,961.74,1120.34,14.798889,5.748889,2.107778,95.555556,66.111111,1007.800000
2020-12-28,2105.61,900.47,14.835556,10.088889,9.302222,78.888889,68.333333,989.888889
2020-12-29,3328.21,940.07,14.881111,9.993333,6.098889,63.333333,71.444444,999.288889
2020-12-30,3329.31,867.36,14.932222,8.373333,7.471111,72.222222,71.777778,1007.766667
2020-12-31,943.49,611.74,14.991111,8.981111,2.743333,86.666667,86.444444,1009.944444

In [ ]:
corr = df.corr()
corr

,Gb(i),Gd(i),H_sun,T2m,WS10m,Wdir,Humidity,Pressure
Gb(i),1.000000,0.136039,0.526446,0.431744,-0.119695,0.126496,-0.690245,0.173616
Gd(i),0.136039,1.000000,0.709614,0.402033,-0.138376,0.052610,-0.280537,-0.181152
H_sun,0.526446,0.709614,1.000000,0.723134,-0.185974,0.111626,-0.565597,-0.182684
T2m,0.431744,0.402033,0.723134,1.000000,-0.233465,0.080201,-0.461840,-0.030233
WS10m,-0.119695,-0.138376,-0.185974,-0.233465,1.000000,0.003811,-0.146000,-0.259881
Wdir,0.126496,0.052610,0.111626,0.080201,0.003811,1.000000,-0.107259,0.004040
Humidity,-0.690245,-0.280537,-0.565597,-0.461840,-0.146000,-0.107259,1.000000,-0.034247
Pressure,0.173616,-0.181152,-0.182684,-0.030233,-0.259881,0.004040,-0.034247,1.000000

In [ ]:
# df = df[['Gb(i)',	'Gd(i)',	'H_sun',	'T2m']]
# df

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler = scaler.fit(df)
df = scaler.transform(df)

df

array([[-0.50813329, -1.06375817, -1.53100083, ...,  1.02442146,
         0.31026934,  0.63161298],
       [-0.83856846, -1.08909276, -1.52212355, ...,  1.30412867,
        -0.20494049,  0.98171139],
       [-1.33722265, -0.94942647, -1.51271628, ...,  0.74471425,
         0.72412642,  0.17772432],
       ...,
       [-0.4266312 , -0.96304774, -1.55392277, ..., -1.51837135,
         0.95217012, -2.2760628 ],
       [-0.42599383, -1.13865098, -1.54782792, ..., -1.41665963,
         0.97750831, -1.09409337],
       [-1.80840044, -1.75600347, -1.54080559, ..., -1.2513781 ,
         2.09238861, -0.7904682 ]])

In [ ]:
# [[[1], [2], [3], [4], [5]]] [6]
# [[[2], [3], [4], [5], [6]]] [7]
# [[[3], [4], [5], [6], [7]]] [8]

def df_to_X_y(df, window_size=168, output_size = 24):
  # df_as_np = df.to_numpy()
  df_as_np = df
  X = []
  y = []
  for i in range(len(df_as_np)-window_size-output_size):
    row = df_as_np[i:i+window_size]
    X.append(row)
    label = df_as_np[i + window_size:i + window_size + output_size][:,1]
    y.append(label)
  return np.array(X), np.array(y)

In [ ]:
WINDOW_SIZE = 7*4
OUTPUT_SIZE = 7
no_of_variables = 8
X1, y1 = df_to_X_y(df, WINDOW_SIZE, OUTPUT_SIZE)
X1.shape, y1.shape, len(X1)

((1061, 28, 8), (1061, 7), 1061)

In [ ]:
end_train = int(len(X1) * 0.9)
end_val = int(len(X1) * 1)

X_train1, y_train1, time_train = X1[:end_train], y1[:end_train], dateTimeAxis[:end_train]
X_val1, y_val1, time_val = X1[end_train:end_val], y1[end_train:end_val], dateTimeAxis[end_train:end_val]
# X_test1, y_test1, time_test = X1[end_val:-2], y1[end_val:-2], dateTimeAxis[end_val:len(X1)-2]
# X_train1.shape, y_train1.shape, X_val1.shape, y_val1.shape, X_test1.shape, y_test1.shape

In [ ]:

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.losses import MeanSquaredError
from tensorflow.keras.metrics import RootMeanSquaredError
from tensorflow.keras.optimizers import Adam

# model1 = Sequential()
# model1.add(InputLayer((24, 8)))
# model1.add(LSTM(64))
# model1.add(Dense(8, 'relu'))
# model1.add(Dense(1, 'linear'))

# model1 = Sequential()
# model1.add(LSTM(100, activation='tanh', input_shape=(24,8), return_sequences=True))
# model1.add(LSTM(75, activation='tanh', return_sequences=False))
# model1.add(Dropout(0.2))
# model1.add(Dense(1))

# model1 = Sequential()
# model1.add(InputLayer((WINDOW_SIZE, 4)))
# model1.add(LSTM(32, return_sequences=True))
# model1.add(LSTM(64))
# model1.add(Dense(8, 'relu'))
# model1.add(Dense(1, 'linear'))

model1 = Sequential()
model1.add(LSTM(64, activation='relu', input_shape=(WINDOW_SIZE, no_of_variables), return_sequences=True))
model1.add(LSTM(32, activation='relu', return_sequences=False))
model1.add(Dropout(0.2))
model1.add(Dense(OUTPUT_SIZE))

model1.summary()

WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 lstm (LSTM)                 (None, 28, 64)            18688

 lstm_1 (LSTM)               (None, 32)                12416

 dropout (Dropout)           (None, 32)                0

 dense (Dense)               (None, 7)                 231

=================================================================
Total params: 31,335
Trainable params: 31,335
Non-trainable params: 0
_________________________________________________________________

In [ ]:
cp1 = ModelCheckpoint('model/', save_best_only=True)
model1.compile(loss='mean_squared_error', optimizer=Adam(learning_rate=0.001), metrics = ['mse'])

In [ ]:
model1.fit(X_train1, y_train1, validation_data=(X_val1, y_val1), batch_size=16, epochs=100, callbacks=[cp1])

Epoch 1/100
60/60 [==============================] - 24s 212ms/step - loss: 0.8164 - mse: 0.8164 - val_loss: 0.2826 - val_mse: 0.2826
Epoch 2/100
60/60 [==============================] - 8s 137ms/step - loss: 0.6082 - mse: 0.6082 - val_loss: 0.3055 - val_mse: 0.3055
Epoch 3/100
60/60 [==============================] - 10s 172ms/step - loss: 0.5568 - mse: 0.5568 - val_loss: 0.2752 - val_mse: 0.2752
Epoch 4/100
60/60 [==============================] - 11s 182ms/step - loss: 0.5295 - mse: 0.5295 - val_loss: 0.2537 - val_mse: 0.2537
Epoch 5/100
60/60 [==============================] - 8s 133ms/step - loss: 0.5154 - mse: 0.5154 - val_loss: 0.2599 - val_mse: 0.2599
Epoch 6/100
60/60 [==============================] - 8s 132ms/step - loss: 0.5072 - mse: 0.5072 - val_loss: 0.2922 - val_mse: 0.2922
Epoch 7/100
60/60 [==============================] - 6s 106ms/step - loss: 0.4907 - mse: 0.4907 - val_loss: 0.2543 - val_mse: 0.2543
Epoch 8/100
60/60 [==============================] - 8s 130ms/step - loss: 0.4864 - mse: 0.4864 - val_loss: 0.2656 - val_mse: 0.2656
Epoch 9/100
60/60 [==============================] - 6s 107ms/step - loss: 0.4846 - mse: 0.4846 - val_loss: 0.2579 - val_mse: 0.2579
Epoch 10/100
60/60 [==============================] - 8s 131ms/step - loss: 0.4764 - mse: 0.4764 - val_loss: 0.2761 - val_mse: 0.2761
Epoch 11/100
60/60 [==============================] - 10s 174ms/step - loss: 0.4794 - mse: 0.4794 - val_loss: 0.2512 - val_mse: 0.2512
Epoch 12/100
60/60 [==============================] - 7s 114ms/step - loss: 0.4714 - mse: 0.4714 - val_loss: 0.2713 - val_mse: 0.2713
Epoch 13/100
60/60 [==============================] - 8s 129ms/step - loss: 0.4695 - mse: 0.4695 - val_loss: 0.3202 - val_mse: 0.3202
Epoch 14/100
60/60 [==============================] - 7s 110ms/step - loss: 0.4719 - mse: 0.4719 - val_loss: 0.2773 - val_mse: 0.2773
Epoch 15/100
60/60 [==============================] - 8s 124ms/step - loss: 0.4651 - mse: 0.4651 - val_loss: 0.2521 - val_mse: 0.2521
Epoch 16/100
60/60 [==============================] - 12s 196ms/step - loss: 0.4650 - mse: 0.4650 - val_loss: 0.2447 - val_mse: 0.2447
Epoch 17/100
60/60 [==============================] - 7s 115ms/step - loss: 0.4588 - mse: 0.4588 - val_loss: 0.2726 - val_mse: 0.2726
Epoch 18/100
60/60 [==============================] - 7s 123ms/step - loss: 0.4496 - mse: 0.4496 - val_loss: 0.2452 - val_mse: 0.2452
Epoch 19/100
60/60 [==============================] - 8s 130ms/step - loss: 0.4548 - mse: 0.4548 - val_loss: 0.2821 - val_mse: 0.2821
Epoch 20/100
60/60 [==============================] - 6s 107ms/step - loss: 0.4488 - mse: 0.4488 - val_loss: 0.2699 - val_mse: 0.2699
Epoch 21/100
60/60 [==============================] - 9s 144ms/step - loss: 0.4545 - mse: 0.4545 - val_loss: 0.3203 - val_mse: 0.3203
Epoch 22/100
60/60 [==============================] - 7s 116ms/step - loss: 0.4436 - mse: 0.4436 - val_loss: 0.2543 - val_mse: 0.2543
Epoch 23/100
60/60 [==============================] - 11s 176ms/step - loss: 0.4406 - mse: 0.4406 - val_loss: 0.2402 - val_mse: 0.2402
Epoch 24/100
60/60 [==============================] - 8s 133ms/step - loss: 0.4405 - mse: 0.4405 - val_loss: 0.2668 - val_mse: 0.2668
Epoch 25/100
60/60 [==============================] - 11s 179ms/step - loss: 0.4404 - mse: 0.4404 - val_loss: 0.2402 - val_mse: 0.2402
Epoch 26/100
60/60 [==============================] - 6s 108ms/step - loss: 0.4399 - mse: 0.4399 - val_loss: 0.2546 - val_mse: 0.2546
Epoch 27/100
60/60 [==============================] - 8s 128ms/step - loss: 0.4372 - mse: 0.4372 - val_loss: 0.2442 - val_mse: 0.2442
Epoch 28/100
60/60 [==============================] - 11s 186ms/step - loss: 0.4327 - mse: 0.4327 - val_loss: 0.2365 - val_mse: 0.2365
Epoch 29/100
60/60 [==============================] - 10s 174ms/step - loss: 0.4361 - mse: 0.4361 - val_loss: 0.2278 - val_mse: 0.2278
Epoch 30/100
60/60 [==============================] - 6s 108ms/step - loss: 0.4264 - mse: 0.4264 - val_loss: 0.2819 - val_mse: 0.2819
Epoch 31/100
60/60 [==============================] - 8s 132ms/step - loss: 0.4249 - mse: 0.4249 - val_loss: 0.2404 - val_mse: 0.2404
Epoch 32/100
60/60 [==============================] - 7s 110ms/step - loss: 0.4256 - mse: 0.4256 - val_loss: 0.2599 - val_mse: 0.2599
Epoch 33/100
60/60 [==============================] - 8s 131ms/step - loss: 0.4252 - mse: 0.4252 - val_loss: 0.2555 - val_mse: 0.2555
Epoch 34/100
60/60 [==============================] - 7s 121ms/step - loss: 0.4251 - mse: 0.4251 - val_loss: 0.2548 - val_mse: 0.2548
Epoch 35/100
60/60 [==============================] - 7s 115ms/step - loss: 0.4220 - mse: 0.4220 - val_loss: 0.2551 - val_mse: 0.2551
Epoch 36/100
60/60 [==============================] - 8s 132ms/step - loss: 0.4198 - mse: 0.4198 - val_loss: 0.2675 - val_mse: 0.2675
Epoch 37/100
60/60 [==============================] - 6s 108ms/step - loss: 0.4197 - mse: 0.4197 - val_loss: 0.2589 - val_mse: 0.2589
Epoch 38/100
60/60 [==============================] - 8s 135ms/step - loss: 0.4161 - mse: 0.4161 - val_loss: 0.2794 - val_mse: 0.2794
Epoch 39/100
60/60 [==============================] - 7s 110ms/step - loss: 0.4206 - mse: 0.4206 - val_loss: 0.2671 - val_mse: 0.2671
Epoch 40/100
60/60 [==============================] - 8s 136ms/step - loss: 0.4149 - mse: 0.4149 - val_loss: 0.2580 - val_mse: 0.2580
Epoch 41/100
60/60 [==============================] - 8s 134ms/step - loss: 0.4142 - mse: 0.4142 - val_loss: 0.2504 - val_mse: 0.2504
Epoch 42/100
60/60 [==============================] - 7s 110ms/step - loss: 0.4089 - mse: 0.4089 - val_loss: 0.2821 - val_mse: 0.2821
Epoch 43/100
60/60 [==============================] - 8s 131ms/step - loss: 0.4082 - mse: 0.4082 - val_loss: 0.2836 - val_mse: 0.2836
Epoch 44/100
60/60 [==============================] - 7s 111ms/step - loss: 0.4011 - mse: 0.4011 - val_loss: 0.2827 - val_mse: 0.2827
Epoch 45/100
60/60 [==============================] - 8s 132ms/step - loss: 0.3962 - mse: 0.3962 - val_loss: 0.2777 - val_mse: 0.2777
Epoch 46/100
60/60 [==============================] - 8s 132ms/step - loss: 0.4015 - mse: 0.4015 - val_loss: 0.2947 - val_mse: 0.2947
Epoch 47/100
60/60 [==============================] - 7s 108ms/step - loss: 0.3961 - mse: 0.3961 - val_loss: 0.2930 - val_mse: 0.2930
Epoch 48/100
60/60 [==============================] - 8s 129ms/step - loss: 0.4027 - mse: 0.4027 - val_loss: 0.3175 - val_mse: 0.3175
Epoch 49/100
60/60 [==============================] - 6s 108ms/step - loss: 0.3974 - mse: 0.3974 - val_loss: 0.3246 - val_mse: 0.3246
Epoch 50/100
60/60 [==============================] - 8s 136ms/step - loss: 0.3910 - mse: 0.3910 - val_loss: 0.3362 - val_mse: 0.3362
Epoch 51/100
60/60 [==============================] - 6s 108ms/step - loss: 0.3944 - mse: 0.3944 - val_loss: 0.3163 - val_mse: 0.3163
Epoch 52/100
60/60 [==============================] - 8s 136ms/step - loss: 0.3826 - mse: 0.3826 - val_loss: 0.3505 - val_mse: 0.3505
Epoch 53/100
60/60 [==============================] - 8s 132ms/step - loss: 0.3838 - mse: 0.3838 - val_loss: 0.3508 - val_mse: 0.3508
Epoch 54/100
60/60 [==============================] - 7s 109ms/step - loss: 0.3852 - mse: 0.3852 - val_loss: 0.3369 - val_mse: 0.3369
Epoch 55/100
60/60 [==============================] - 8s 133ms/step - loss: 0.3825 - mse: 0.3825 - val_loss: 0.3922 - val_mse: 0.3922
Epoch 56/100
60/60 [==============================] - 7s 109ms/step - loss: 0.3754 - mse: 0.3754 - val_loss: 0.3887 - val_mse: 0.3887
Epoch 57/100
60/60 [==============================] - 8s 133ms/step - loss: 0.3739 - mse: 0.3739 - val_loss: 0.3988 - val_mse: 0.3988
Epoch 58/100
60/60 [==============================] - 8s 127ms/step - loss: 0.3751 - mse: 0.3751 - val_loss: 0.3917 - val_mse: 0.3917
Epoch 59/100
60/60 [==============================] - 7s 114ms/step - loss: 0.3701 - mse: 0.3701 - val_loss: 0.3696 - val_mse: 0.3696
Epoch 60/100
60/60 [==============================] - 8s 133ms/step - loss: 0.3731 - mse: 0.3731 - val_loss: 0.3393 - val_mse: 0.3393
Epoch 61/100
60/60 [==============================] - 7s 110ms/step - loss: 0.3645 - mse: 0.3645 - val_loss: 0.3961 - val_mse: 0.3961
Epoch 62/100
60/60 [==============================] - 8s 133ms/step - loss: 0.3588 - mse: 0.3588 - val_loss: 0.3775 - val_mse: 0.3775
Epoch 63/100
60/60 [==============================] - 7s 118ms/step - loss: 0.3598 - mse: 0.3598 - val_loss: 0.4120 - val_mse: 0.4120
Epoch 64/100
60/60 [==============================] - 8s 129ms/step - loss: 0.3591 - mse: 0.3591 - val_loss: 0.3713 - val_mse: 0.3713
Epoch 65/100
60/60 [==============================] - 8s 132ms/step - loss: 0.3543 - mse: 0.3543 - val_loss: 0.4116 - val_mse: 0.4116
Epoch 66/100
60/60 [==============================] - 7s 112ms/step - loss: 0.3552 - mse: 0.3552 - val_loss: 0.4428 - val_mse: 0.4428
Epoch 67/100
60/60 [==============================] - 8s 132ms/step - loss: 0.3498 - mse: 0.3498 - val_loss: 0.4556 - val_mse: 0.4556
Epoch 68/100
60/60 [==============================] - 6s 108ms/step - loss: 0.3496 - mse: 0.3496 - val_loss: 0.4503 - val_mse: 0.4503
Epoch 69/100
60/60 [==============================] - 8s 128ms/step - loss: 0.3398 - mse: 0.3398 - val_loss: 0.3959 - val_mse: 0.3959
Epoch 70/100
60/60 [==============================] - 8s 129ms/step - loss: 0.3375 - mse: 0.3375 - val_loss: 0.4286 - val_mse: 0.4286
Epoch 71/100
60/60 [==============================] - 7s 113ms/step - loss: 0.3342 - mse: 0.3342 - val_loss: 0.4269 - val_mse: 0.4269
Epoch 72/100
60/60 [==============================] - 8s 131ms/step - loss: 0.3356 - mse: 0.3356 - val_loss: 0.4522 - val_mse: 0.4522
Epoch 73/100
60/60 [==============================] - 6s 107ms/step - loss: 0.3361 - mse: 0.3361 - val_loss: 0.4554 - val_mse: 0.4554
Epoch 74/100
60/60 [==============================] - 8s 132ms/step - loss: 0.3277 - mse: 0.3277 - val_loss: 0.4793 - val_mse: 0.4793
Epoch 75/100
60/60 [==============================] - 6s 106ms/step - loss: 0.3259 - mse: 0.3259 - val_loss: 0.4513 - val_mse: 0.4513
Epoch 76/100
60/60 [==============================] - 8s 134ms/step - loss: 0.3303 - mse: 0.3303 - val_loss: 0.4192 - val_mse: 0.4192
Epoch 77/100
60/60 [==============================] - 8s 133ms/step - loss: 0.3196 - mse: 0.3196 - val_loss: 0.4395 - val_mse: 0.4395
Epoch 78/100
60/60 [==============================] - 7s 110ms/step - loss: 0.3208 - mse: 0.3208 - val_loss: 0.4431 - val_mse: 0.4431
Epoch 79/100
60/60 [==============================] - 8s 133ms/step - loss: 0.3140 - mse: 0.3140 - val_loss: 0.4170 - val_mse: 0.4170
Epoch 80/100
60/60 [==============================] - 7s 110ms/step - loss: 0.3165 - mse: 0.3165 - val_loss: 0.4393 - val_mse: 0.4393
Epoch 81/100
60/60 [==============================] - 8s 132ms/step - loss: 0.3246 - mse: 0.3246 - val_loss: 0.4112 - val_mse: 0.4112
Epoch 82/100
60/60 [==============================] - 7s 120ms/step - loss: 0.3106 - mse: 0.3106 - val_loss: 0.4240 - val_mse: 0.4240
Epoch 83/100
60/60 [==============================] - 7s 118ms/step - loss: 0.3143 - mse: 0.3143 - val_loss: 0.4033 - val_mse: 0.4033
Epoch 84/100
60/60 [==============================] - 8s 131ms/step - loss: 0.3113 - mse: 0.3113 - val_loss: 0.4114 - val_mse: 0.4114
Epoch 85/100
60/60 [==============================] - 7s 109ms/step - loss: 0.3121 - mse: 0.3121 - val_loss: 0.4394 - val_mse: 0.4394
Epoch 86/100
60/60 [==============================] - 8s 131ms/step - loss: 0.3114 - mse: 0.3114 - val_loss: 0.4436 - val_mse: 0.4436
Epoch 87/100
60/60 [==============================] - 7s 109ms/step - loss: 0.3099 - mse: 0.3099 - val_loss: 0.4383 - val_mse: 0.4383
Epoch 88/100
60/60 [==============================] - 8s 131ms/step - loss: 0.3108 - mse: 0.3108 - val_loss: 0.4561 - val_mse: 0.4561
Epoch 89/100
60/60 [==============================] - 8s 130ms/step - loss: 0.3058 - mse: 0.3058 - val_loss: 0.4746 - val_mse: 0.4746
Epoch 90/100
60/60 [==============================] - 6s 107ms/step - loss: 0.3040 - mse: 0.3040 - val_loss: 0.4357 - val_mse: 0.4357
Epoch 91/100
60/60 [==============================] - 8s 133ms/step - loss: 0.3019 - mse: 0.3019 - val_loss: 0.4456 - val_mse: 0.4456
Epoch 92/100
60/60 [==============================] - 6s 108ms/step - loss: 0.3005 - mse: 0.3005 - val_loss: 0.4422 - val_mse: 0.4422
Epoch 93/100
60/60 [==============================] - 8s 131ms/step - loss: 0.2985 - mse: 0.2985 - val_loss: 0.4783 - val_mse: 0.4783
Epoch 94/100
60/60 [==============================] - 6s 107ms/step - loss: 0.2970 - mse: 0.2970 - val_loss: 0.4848 - val_mse: 0.4848
Epoch 95/100
60/60 [==============================] - 8s 136ms/step - loss: 0.2973 - mse: 0.2973 - val_loss: 0.4358 - val_mse: 0.4358
Epoch 96/100
60/60 [==============================] - 8s 132ms/step - loss: 0.2932 - mse: 0.2932 - val_loss: 0.4352 - val_mse: 0.4352
Epoch 97/100
60/60 [==============================] - 6s 108ms/step - loss: 0.2965 - mse: 0.2965 - val_loss: 0.4297 - val_mse: 0.4297
Epoch 98/100
60/60 [==============================] - 8s 132ms/step - loss: 0.2934 - mse: 0.2934 - val_loss: 0.4545 - val_mse: 0.4545
Epoch 99/100
60/60 [==============================] - 6s 108ms/step - loss: 0.2914 - mse: 0.2914 - val_loss: 0.4291 - val_mse: 0.4291
Epoch 100/100
60/60 [==============================] - 8s 129ms/step - loss: 0.2909 - mse: 0.2909 - val_loss: 0.4140 - val_mse: 0.4140

In [ ]:
from tensorflow.keras.models import load_model
model1 = load_model('model/')

WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.
WARNING:tensorflow:Layer lstm_1 will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.

In [ ]:
from sklearn.metrics import mean_squared_error as mse
import matplotlib.pyplot as plt

def plot_predictions1(model, X, y, time, start=0, end=200):
  predictions = model.predict(X)

  # prediction_copies = np.tile(np.array([predictions]).transpose(), (1, no_of_variables))
  # predictions_rescale = scaler.inverse_transform(prediction_copies)[:,0]

  # y_copies = np.tile(np.array([y]).transpose(), (1, no_of_variables))
  # y_rescale = scaler.inverse_transform(y_copies)[:,0]

  # df_local = pd.DataFrame(data={'Predictions':predictions_rescale, 'Actuals':y_rescale})
  # df_local.index = time
  # plt.plot(df_local['Predictions'][start:end], color='orange')
  # plt.plot(df_local['Actuals'][start:end], color='skyblue')
  # plt.gcf().autofmt_xdate()
  # return df_local, mse(y, predictions)
  print(predictions.shape)
  return mse(y, predictions)

In [ ]:
# res, error = plot_predictions1(model1, X_train1, y_train1, time_train)
# res
# error

In [ ]:
# res, error = plot_predictions1(model1, X_val1, y_val1, time_val)
# error

In [ ]:
# res, error = plot_predictions1(model1, X_test1, y_test1, time_test)
# res
# error

In [ ]:
# !zip -r /content/model3.zip /content/model3
# !zip -r /content/model4.zip /content/model4